(define (problem simplevoltageprob)
(:domain simplevoltage)
(:init
    (begin)
    (p)
    (at 0.1 (not(begin)))
    (is-not-increasing)
    (is-not-decreasing)
    (=(battery-soc-bg)50)
    (=(lb)40)
    (=(ub)99)

    (at 6 (=(battery-soc-bg)80))
    (at 8 (=(battery-soc-bg)100))
    (at 12 (=(battery-soc-bg)50))
    (at 14 (=(battery-soc-bg)40))
    (at 24(horizon))
)

(:goal(and (done)
;(=(voltage-adj)4)
)
)
)