(define (problem simplevoltageprob)
(:domain simplevoltage)
(:init
    (begin)
    (p)
    ;(not (horizon))
    (at 0.1 (not(begin)))
    
    (=(bgvoltage)15)
    (=(voltage-adj)0)
    (=(lb)10)
    (=(ub)20)
    ;(at 2 (=(bgvoltage)15))
    (at 5 ( =(bgvoltage)21))
    (at 8 ( =(bgvoltage)25))
    ;(at 6 ( =(bgvoltage)22))
   ; (at 9 ( =(bgvoltage)18))  ;24-2-2 is ok, but 25-2-2-2will take time to 7
    ;(at 8 ( =(bgvoltage)8))
    ;(at 7( =(bgvoltage)24))
    ;(at 8( =(bgvoltage)21))
    ;(at 9( =(bgvoltage)17))
    ;(at 8 (=(bgvoltage)10))
   (at 10(horizon))
)

(:goal(and (done)
;(=(voltage-adj)4)
)
)
)