(define (problem simplevoltageprob)
(:domain simplevoltage)
(:init
    (begin)
    (p)
    ;(not (horizon))
    (at 0.1 (not(begin)))
    (=(bgvoltage)15)
    (=(voltage-adj)0)
    (=(lb)10)
    (=(ub)20)
    (at 5( =(bgvoltage)9))
    (at 6( =(bgvoltage)10))
    (at 7( =(bgvoltage)5))
    ;(at 7( =(bgvoltage)24))
    ;(at 8( =(bgvoltage)21))
    ;(at 9( =(bgvoltage)17))
    ;(at 8 (=(bgvoltage)10))
   (at 20(horizon))
)

(:goal(and (done)
;(=(voltage-adj)4)
)
)
)